// TeleCaller AI — Onboarding Consent Screen
// Shown once to first-time Google Sign-In users.
// Requires acceptance of Privacy Policy, Terms & Conditions, and Guidelines.

import React, {useState, useRef} from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  StatusBar,
  Animated,
  Linking,
  ActivityIndicator,
  Image,
} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import Icon from 'react-native-vector-icons/MaterialCommunityIcons';
import {Colors, FontSize, BorderRadius, Shadow, Spacing} from '../../theme';

// ─────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────
interface ConsentItem {
  id: 'privacy' | 'terms' | 'guidelines';
  icon: string;
  color: string;
  title: string;
  subtitle: string;
}

const CONSENT_ITEMS: ConsentItem[] = [
  {
    id: 'privacy',
    icon: 'shield-lock-outline',
    color: '#6C63FF',
    title: 'Privacy Policy',
    subtitle: 'How we handle your data, recordings & third-party integrations',
  },
  {
    id: 'terms',
    icon: 'file-document-outline',
    color: '#00B09B',
    title: 'Terms & Conditions',
    subtitle: 'Rules governing your use of Audify AI',
  },
  {
    id: 'guidelines',
    icon: 'compass-outline',
    color: '#F7971E',
    title: 'Usage Guidelines',
    subtitle: 'Best practices and responsible use of AI transcription',
  },
];

// ─────────────────────────────────────────────────────────────
// Section Content
// ─────────────────────────────────────────────────────────────
const PRIVACY_POLICY = `Last updated: September 25, 2026
Effective Date: September 25, 2026

Audify AI ("we", "us", or "our") is committed to transparent and secure handling of user information. This Privacy Policy details how data is accessed, processed, and safeguarded.

1. DATA WE ACCESS & PROCESS
• Google Account Info: When you sign in with Google OAuth, we receive your name, email address, profile picture, and tokens to authenticate API access to your Google Drive and Google Sheets.
• Call Recordings (Audio): Audio files stored on your device that you grant access to via Android Storage Access Framework. Audio files are NEVER uploaded to or stored on our servers.
• Call Metadata: File names, durations, timestamps, and caller details matched from your local device call logs to organize records and sync with your connected Google Sheet.
• Transcripts & AI Summaries: Text transcripts and analysis generated via speech-to-text APIs. Stored locally on your device and inside your designated personal Google Sheet or Google Drive folder.

2. THIRD-PARTY SERVICES & AI PROCESSING
• Google OAuth & APIs: Used with restricted scopes (drive.file and spreadsheets) to create and access only files generated by this application.
• Speech-to-Text & AI APIs: When you initiate transcription or enable background processing queues, audio snippets are submitted to the configured API for transcription and summarization.
• Zero Data Selling: We do not sell, rent, or lease your personal data, audio recordings, or transcripts to any third-party broker or advertiser.

3. DATA RETENTION & SECURITY
• Device-First Architecture: Recordings remain on your physical device and in your personal cloud accounts.
• Security: Authentication tokens are secured using Android Keystore-backed encrypted storage.
• Deletion: You can delete recordings, clear app cache, or sign out at any time. Revoke Google access anytime via your Google Account Permissions.

4. CONTACT & INQUIRIES
For privacy inquiries, help, or support: prajwalnair2603@gmail.com`;

const TERMS_AND_CONDITIONS = `Last updated: September 25, 2026
Effective Date: September 25, 2026

By installing or using Audify AI, you agree to these Terms & Conditions.

1. ELIGIBILITY & ACCEPTANCE
• You must be at least 18 years of age (or legal age in your jurisdiction) to use this application.
• You agree to use the application solely for lawful business management and personal organizational purposes.

2. COMPLIANCE WITH CALL RECORDING LAWS (CRITICAL)
• User Sole Responsibility: Laws governing telephone recording consent vary by jurisdiction (one-party vs. all-party/two-party consent).
• Consent Obligation: You warrant and represent that you have obtained all required consents from all parties on every call before recording or importing audio.
• Indemnification: Audify AI disclaims all liability for unlawful or non-consensual recordings. You agree to indemnify and hold harmless Audify AI and its operators from any legal actions or claims arising from violation of recording statutes.

3. AI ACCURACY & RELIANCE DISCLAIMER
• Automated Technology: Transcription, sentiment analysis, and summaries are generated by automated artificial intelligence models.
• No Warranty of Accuracy: Output may contain errors, omissions, or misinterpretations due to audio quality, speech accents, or model limitations.
• Verification Required: Transcripts must be independently verified by a human before relying on them for legal, financial, medical, or high-stakes business decisions.

4. THIRD-PARTY APIS & BILLING
• If you provide your own API keys or endpoints, you are solely responsible for usage costs, rate limits, and compliance with the terms of those providers.

5. PROHIBITED USES
• Unlawful surveillance, wiretapping, stalking, or harassment.
• Reverse-engineering, decompiling, or redistributing the application.
• Uploading malicious code or infringing intellectual property.

6. LIMITATION OF LIABILITY
• Audify AI is provided "AS IS" and "AS AVAILABLE" without warranties of any kind. To the maximum extent permitted by law, liability is limited strictly to amounts paid, if any.`;

const USAGE_GUIDELINES = `Responsible Use Guidelines for Audify AI:

✅ DO:
• Always notify and obtain explicit consent from all call participants before recording or transcribing.
• Review and verify AI transcripts manually before taking consequential business or legal actions.
• Regularly back up recordings to your personal Google Drive and delete unneeded device files.
• Protect sensitive customer information by restricting access to your exported Google Sheets.
• Use Wi-Fi connections when performing large batch uploads to avoid mobile data charges.

❌ DON'T:
• NEVER record or transcribe phone calls in violation of local consent laws.
• Do not process or transcribe sensitive financial credentials (credit cards, CVVs), passwords, or protected medical data without appropriate compliance controls.
• Do not share exported transcripts containing confidential customer information with unauthorized third parties.
• Do not rely on automated AI sentiment or summaries as definitive legal or employment records without human corroboration.

🤖 AI SPEECH RECOGNITION NOTES:
• Background noise, low call volume, and heavy accents may reduce transcription accuracy.
• Always treat initial AI output as an unverified draft.

📱 STORAGE & BACKUP TIPS:
• Designate your exact phone call recording folder in Settings.
• Manage local device storage regularly as recordings are preserved until manually deleted.

Support & Inquiries: prajwalnair2603@gmail.com`;

// ─────────────────────────────────────────────────────────────
// Expandable Policy Section
// ─────────────────────────────────────────────────────────────
interface PolicySectionProps {
  item: ConsentItem;
  content: string;
  isChecked: boolean;
  onCheck: () => void;
}

const PolicySection: React.FC<PolicySectionProps> = ({
  item,
  content,
  isChecked,
  onCheck,
}) => {
  const [expanded, setExpanded] = useState(false);
  const rotateAnim = useRef(new Animated.Value(0)).current;
  const checkScale = useRef(new Animated.Value(1)).current;

  const toggleExpand = () => {
    const toValue = expanded ? 0 : 1;
    Animated.spring(rotateAnim, {
      toValue,
      useNativeDriver: true,
      speed: 20,
    }).start();
    setExpanded(!expanded);
  };

  const handleCheck = () => {
    Animated.sequence([
      Animated.timing(checkScale, {toValue: 0.8, duration: 80, useNativeDriver: true}),
      Animated.spring(checkScale, {toValue: 1, useNativeDriver: true, speed: 25}),
    ]).start();
    onCheck();
  };

  const rotate = rotateAnim.interpolate({
    inputRange: [0, 1],
    outputRange: ['0deg', '180deg'],
  });

  return (
    <View style={styles.policyCard}>
      {/* Card Header */}
      <TouchableOpacity
        style={styles.policyHeader}
        onPress={toggleExpand}
        activeOpacity={0.8}
        accessibilityRole="button"
        accessibilityLabel={`${item.title} — tap to expand`}>
        <View style={[styles.policyIconBadge, {backgroundColor: item.color + '20'}]}>
          <Icon name={item.icon} size={22} color={item.color} />
        </View>
        <View style={styles.policyMeta}>
          <Text style={styles.policyTitle}>{item.title}</Text>
          <Text style={styles.policySubtitle}>{item.subtitle}</Text>
        </View>
        <Animated.View style={{transform: [{rotate}]}}>
          <Icon name="chevron-down" size={20} color={Colors.textTertiary} />
        </Animated.View>
      </TouchableOpacity>

      {/* Expandable Content */}
      {expanded && (
        <View style={styles.policyContent}>
          <ScrollView
            style={styles.policyScroll}
            nestedScrollEnabled
            showsVerticalScrollIndicator={true}
            scrollIndicatorInsets={{right: 1}}>
            <Text style={styles.policyText}>{content}</Text>
          </ScrollView>
          <View style={styles.policyReadNote}>
            <Icon name="check-circle-outline" size={13} color={Colors.success} />
            <Text style={styles.policyReadNoteText}>
              Please read the full policy above before accepting
            </Text>
          </View>
        </View>
      )}

      {/* Accept Checkbox Row */}
      <TouchableOpacity
        style={styles.checkRow}
        onPress={handleCheck}
        activeOpacity={0.8}
        accessibilityRole="checkbox"
        accessibilityState={{checked: isChecked}}
        accessibilityLabel={`I have read and accept the ${item.title}`}>
        <Animated.View
          style={[
            styles.checkbox,
            isChecked && styles.checkboxChecked,
            {transform: [{scale: checkScale}]},
          ]}>
          {isChecked && (
            <Icon name="check-bold" size={13} color={Colors.textInverse} />
          )}
        </Animated.View>
        <Text style={[styles.checkLabel, isChecked && styles.checkLabelChecked]}>
          I have read and agree to the{' '}
          <Text style={[styles.checkLabelBold, {color: item.color}]}>
            {item.title}
          </Text>
        </Text>
      </TouchableOpacity>
    </View>
  );
};

// ─────────────────────────────────────────────────────────────
// Main Screen
// ─────────────────────────────────────────────────────────────
interface OnboardingConsentScreenProps {
  onAccept: () => void;
}

const OnboardingConsentScreen: React.FC<OnboardingConsentScreenProps> = ({
  onAccept,
}) => {
  const [checked, setChecked] = useState({
    privacy: false,
    terms: false,
    guidelines: false,
  });
  const [isSubmitting, setIsSubmitting] = useState(false);

  const allAccepted = checked.privacy && checked.terms && checked.guidelines;

  const toggle = (id: 'privacy' | 'terms' | 'guidelines') => {
    setChecked(prev => ({...prev, [id]: !prev[id]}));
  };

  const handleContinue = async () => {
    if (!allAccepted) return;
    setIsSubmitting(true);
    // Small delay for UX feedback, then callback
    setTimeout(() => {
      onAccept();
    }, 600);
  };

  const contentFor = (id: ConsentItem['id']) => {
    if (id === 'privacy') return PRIVACY_POLICY;
    if (id === 'terms') return TERMS_AND_CONDITIONS;
    return USAGE_GUIDELINES;
  };

  const acceptedCount = Object.values(checked).filter(Boolean).length;

  return (
    <SafeAreaView style={styles.safeArea} edges={['top', 'bottom']}>
      <StatusBar barStyle="light-content" />

      {/* ── Gradient-style Header ── */}
      <View style={styles.header}>
        <View style={styles.headerLogoRow}>
          <Image
            source={require('../../assets/logo_icon_transparent.png')}
            style={styles.logoMarkImage}
            resizeMode="contain"
          />
          <Text style={styles.headerBrand}>Audify AI</Text>
        </View>
        <Text style={styles.headerTitle}>Before You Begin</Text>
        <Text style={styles.headerSubtitle}>
          Please review and accept our policies to protect your privacy and ensure
          responsible use of the app.
        </Text>

        {/* Progress Pills */}
        <View style={styles.progressRow}>
          {CONSENT_ITEMS.map(item => (
            <View
              key={item.id}
              style={[
                styles.progressPill,
                checked[item.id] && {backgroundColor: item.color},
              ]}>
              {checked[item.id] ? (
                <Icon name="check" size={11} color="#fff" />
              ) : (
                <View style={styles.progressDot} />
              )}
            </View>
          ))}
          <Text style={styles.progressText}>{acceptedCount}/3 accepted</Text>
        </View>
      </View>

      {/* ── Scrollable Policy Sections ── */}
      <ScrollView
        style={styles.scrollArea}
        contentContainerStyle={styles.scrollContent}
        showsVerticalScrollIndicator={false}
        keyboardShouldPersistTaps="handled">

        <Text style={styles.sectionHint}>
          Tap each section to read, then check the box to accept.
        </Text>

        {CONSENT_ITEMS.map(item => (
          <PolicySection
            key={item.id}
            item={item}
            content={contentFor(item.id)}
            isChecked={checked[item.id]}
            onCheck={() => toggle(item.id)}
          />
        ))}

        {/* Disclaimer note */}
        <View style={styles.disclaimer}>
          <Icon name="information-outline" size={14} color={Colors.textTertiary} />
          <Text style={styles.disclaimerText}>
            By continuing, you confirm you are 18 years or older and have the
            authority to accept these terms on behalf of your organization.
          </Text>
        </View>

        {/* ── Continue Button ── */}
        <TouchableOpacity
          style={[
            styles.continueBtn,
            allAccepted ? styles.continueBtnActive : styles.continueBtnDisabled,
          ]}
          onPress={handleContinue}
          disabled={!allAccepted || isSubmitting}
          activeOpacity={0.85}
          accessibilityLabel="Continue to the app"
          accessibilityRole="button">
          {isSubmitting ? (
            <ActivityIndicator size="small" color="#fff" />
          ) : (
            <>
              <Icon
                name={allAccepted ? 'rocket-launch-outline' : 'lock-outline'}
                size={20}
                color={allAccepted ? '#fff' : Colors.textTertiary}
              />
              <Text
                style={[
                  styles.continueBtnText,
                  !allAccepted && styles.continueBtnTextDisabled,
                ]}>
                {allAccepted ? 'Continue to Audify AI' : 'Accept all policies to continue'}
              </Text>
            </>
          )}
        </TouchableOpacity>

        {/* Help & Support Contact Link */}
        <TouchableOpacity
          style={styles.helpRow}
          onPress={() =>
            Linking.openURL(
              'mailto:prajwalnair2603@gmail.com?subject=Audify%20AI%20Support',
            )
          }
          activeOpacity={0.7}
          accessibilityLabel="Contact support"
          accessibilityRole="button">
          <Icon name="email-outline" size={15} color="rgba(255, 255, 255, 0.7)" />
          <Text style={styles.helpText}>
            Need help? Contact{' '}
            <Text style={styles.helpEmail}>prajwalnair2603@gmail.com</Text>
          </Text>
        </TouchableOpacity>

        <View style={{height: 20}} />
      </ScrollView>
    </SafeAreaView>
  );
};

// ─────────────────────────────────────────────────────────────
// Styles
// ─────────────────────────────────────────────────────────────
const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#0F0A2A',
  },
  helpRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: Spacing.md,
    gap: 6,
  },
  helpText: {
    fontSize: FontSize.xs,
    color: 'rgba(255, 255, 255, 0.65)',
  },
  helpEmail: {
    color: '#60A5FA',
    fontWeight: '600',
    textDecorationLine: 'underline',
  },

  // ── Header ──
  header: {
    backgroundColor: '#1A1040',
    paddingHorizontal: Spacing.xl,
    paddingTop: Spacing.lg,
    paddingBottom: Spacing.xl,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    ...(Shadow.lg as object),
  },
  headerLogoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    marginBottom: Spacing.lg,
  },
  logoMarkImage: {
    width: 36,
    height: 36,
  },
  headerBrand: {
    fontSize: FontSize.lg,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: 0.5,
  },
  headerTitle: {
    fontSize: FontSize['3xl'],
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: -0.5,
    marginBottom: Spacing.sm,
  },
  headerSubtitle: {
    fontSize: FontSize.sm,
    color: 'rgba(255,255,255,0.6)',
    lineHeight: 20,
    marginBottom: Spacing.xl,
  },
  progressRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
  },
  progressPill: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.2)',
  },
  progressDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: 'rgba(255,255,255,0.3)',
  },
  progressText: {
    fontSize: FontSize.xs,
    color: 'rgba(255,255,255,0.5)',
    fontWeight: '600',
    marginLeft: Spacing.xs,
  },

  // ── Scroll Area ──
  scrollArea: {
    flex: 1,
    backgroundColor: '#F4F6FB',
  },
  scrollContent: {
    padding: Spacing.xl,
    gap: Spacing.md,
  },
  sectionHint: {
    fontSize: FontSize.xs,
    color: Colors.textTertiary,
    textAlign: 'center',
    marginBottom: Spacing.xs,
    fontStyle: 'italic',
  },

  // ── Policy Card ──
  policyCard: {
    backgroundColor: Colors.surface,
    borderRadius: BorderRadius.xl,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: Colors.border,
    ...(Shadow.sm as object),
  },
  policyHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: Spacing.lg,
    gap: Spacing.md,
  },
  policyIconBadge: {
    width: 46,
    height: 46,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  policyMeta: {
    flex: 1,
  },
  policyTitle: {
    fontSize: FontSize.base,
    fontWeight: '700',
    color: Colors.textPrimary,
    marginBottom: 2,
  },
  policySubtitle: {
    fontSize: FontSize.xs,
    color: Colors.textSecondary,
    lineHeight: 16,
  },
  policyContent: {
    borderTopWidth: 1,
    borderTopColor: Colors.border,
    backgroundColor: Colors.background,
  },
  policyScroll: {
    maxHeight: 240,
    padding: Spacing.lg,
  },
  policyText: {
    fontSize: FontSize.xs,
    color: Colors.textSecondary,
    lineHeight: 20,
    fontFamily: 'monospace',
  },
  policyReadNote: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    paddingHorizontal: Spacing.lg,
    paddingBottom: Spacing.sm,
  },
  policyReadNoteText: {
    fontSize: FontSize.xs,
    color: Colors.textTertiary,
    fontStyle: 'italic',
  },

  // ── Checkbox Row ──
  checkRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
    padding: Spacing.lg,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
    backgroundColor: Colors.surface,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 7,
    borderWidth: 2,
    borderColor: Colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.background,
  },
  checkboxChecked: {
    backgroundColor: Colors.success,
    borderColor: Colors.success,
  },
  checkLabel: {
    flex: 1,
    fontSize: FontSize.sm,
    color: Colors.textSecondary,
    lineHeight: 18,
  },
  checkLabelChecked: {
    color: Colors.textPrimary,
  },
  checkLabelBold: {
    fontWeight: '700',
  },

  // ── Disclaimer ──
  disclaimer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: Spacing.sm,
    backgroundColor: Colors.surfaceSecondary,
    borderRadius: BorderRadius.lg,
    padding: Spacing.md,
    borderWidth: 1,
    borderColor: Colors.border,
    marginTop: Spacing.xs,
  },
  disclaimerText: {
    flex: 1,
    fontSize: FontSize.xs,
    color: Colors.textTertiary,
    lineHeight: 18,
  },

  // ── Continue Button ──
  continueBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.sm,
    paddingVertical: 16,
    borderRadius: BorderRadius.xl,
    marginTop: Spacing.lg,
    ...(Shadow.lg as object),
  },
  continueBtnActive: {
    backgroundColor: '#6C63FF',
  },
  continueBtnDisabled: {
    backgroundColor: Colors.surfaceSecondary,
    borderWidth: 1.5,
    borderColor: Colors.border,
    shadowOpacity: 0,
    elevation: 0,
  },
  continueBtnText: {
    fontSize: FontSize.base,
    fontWeight: '700',
    color: '#fff',
    letterSpacing: 0.2,
  },
  continueBtnTextDisabled: {
    color: Colors.textTertiary,
  },
});

export default OnboardingConsentScreen;
